// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP RMWreg_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
// HiddenMCMC_WEI
Rcpp::List HiddenMCMC_WEI(int N, int thin, int burn, NumericVector Time, NumericVector Cens, NumericMatrix X, double hyp1_gam, double hyp2_gam, NumericVector beta0, double gam0, NumericVector LSbeta0, double LSgam0, double ar, int FixGam, int FixBetaJ, int StoreAdapt, int EndAdapt, int PrintProgress, int Adapt);
RcppExport SEXP RMWreg_HiddenMCMC_WEI(SEXP NSEXP, SEXP thinSEXP, SEXP burnSEXP, SEXP TimeSEXP, SEXP CensSEXP, SEXP XSEXP, SEXP hyp1_gamSEXP, SEXP hyp2_gamSEXP, SEXP beta0SEXP, SEXP gam0SEXP, SEXP LSbeta0SEXP, SEXP LSgam0SEXP, SEXP arSEXP, SEXP FixGamSEXP, SEXP FixBetaJSEXP, SEXP StoreAdaptSEXP, SEXP EndAdaptSEXP, SEXP PrintProgressSEXP, SEXP AdaptSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cens(CensSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type hyp1_gam(hyp1_gamSEXP);
    Rcpp::traits::input_parameter< double >::type hyp2_gam(hyp2_gamSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type gam0(gam0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type LSbeta0(LSbeta0SEXP);
    Rcpp::traits::input_parameter< double >::type LSgam0(LSgam0SEXP);
    Rcpp::traits::input_parameter< double >::type ar(arSEXP);
    Rcpp::traits::input_parameter< int >::type FixGam(FixGamSEXP);
    Rcpp::traits::input_parameter< int >::type FixBetaJ(FixBetaJSEXP);
    Rcpp::traits::input_parameter< int >::type StoreAdapt(StoreAdaptSEXP);
    Rcpp::traits::input_parameter< int >::type EndAdapt(EndAdaptSEXP);
    Rcpp::traits::input_parameter< int >::type PrintProgress(PrintProgressSEXP);
    Rcpp::traits::input_parameter< int >::type Adapt(AdaptSEXP);
    __result = Rcpp::wrap(HiddenMCMC_WEI(N, thin, burn, Time, Cens, X, hyp1_gam, hyp2_gam, beta0, gam0, LSbeta0, LSgam0, ar, FixGam, FixBetaJ, StoreAdapt, EndAdapt, PrintProgress, Adapt));
    return __result;
END_RCPP
}
