# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HiddenWEI_MCMC <- function(N, thin, burn, Time, Event, X, hyp1_gam, hyp2_gam, beta0, gam0, LSbeta0, LSgam0, ar, FixGam, FixBetaJ, StoreAdapt, EndAdapt, PrintProgress, Adapt) {
    .Call('RMWreg_HiddenWEI_MCMC', PACKAGE = 'RMWreg', N, thin, burn, Time, Event, X, hyp1_gam, hyp2_gam, beta0, gam0, LSbeta0, LSgam0, ar, FixGam, FixBetaJ, StoreAdapt, EndAdapt, PrintProgress, Adapt)
}

lambdaUpdate <- function(mixing, Time, Event, X, beta, gam, theta, n) {
    .Call('RMWreg_lambdaUpdate', PACKAGE = 'RMWreg', mixing, Time, Event, X, beta, gam, theta, n)
}

HiddenRMWreg_MCMC <- function(N, thin, burn, Time, Event, X, mixing, hyp1_gam, hyp2_gam, PriorCV, hyp_theta, beta0, gam0, theta0, Adapt, ar, StoreAdapt, EndAdapt, LSbeta0, LSgam0, LStheta0, FixBetaJ, FixGam, FixTheta, PrintProgress) {
    .Call('RMWreg_HiddenRMWreg_MCMC', PACKAGE = 'RMWreg', N, thin, burn, Time, Event, X, mixing, hyp1_gam, hyp2_gam, PriorCV, hyp_theta, beta0, gam0, theta0, Adapt, ar, StoreAdapt, EndAdapt, LSbeta0, LSgam0, LStheta0, FixBetaJ, FixGam, FixTheta, PrintProgress)
}

rcpp_hello <- function() {
    .Call('RMWreg_rcpp_hello', PACKAGE = 'RMWreg')
}

