# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('RMWreg_rcpp_hello', PACKAGE = 'RMWreg')
}

HiddenMCMC_WEI <- function(N, thin, burn, Time, Cens, X, hyp1_gam, hyp2_gam, beta0, gam0, LSbeta0, LSgam0, ar, FixGam, FixBetaJ, StoreAdapt, EndAdapt, PrintProgress, Adapt) {
    .Call('RMWreg_HiddenMCMC_WEI', PACKAGE = 'RMWreg', N, thin, burn, Time, Cens, X, hyp1_gam, hyp2_gam, beta0, gam0, LSbeta0, LSgam0, ar, FixGam, FixBetaJ, StoreAdapt, EndAdapt, PrintProgress, Adapt)
}

HiddenMCMC_RMWreg <- function(N, thin, burn, Time, Cens, X, mixing, hyp1_gam, hyp2_gam, typ_theta, hyp_theta, beta0, gam0, theta0, Adapt, ar, StoreAdapt, EndAdapt, LSbeta0, LSgam0, LStheta0, FixBetaJ, FixGam, FixTheta, PrintProgress) {
    .Call('RMWreg_HiddenMCMC_RMWreg', PACKAGE = 'RMWreg', N, thin, burn, Time, Cens, X, mixing, hyp1_gam, hyp2_gam, typ_theta, hyp_theta, beta0, gam0, theta0, Adapt, ar, StoreAdapt, EndAdapt, LSbeta0, LSgam0, LStheta0, FixBetaJ, FixGam, FixTheta, PrintProgress)
}

